spring:
  spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:yapDb
    driverClassName: org.h2.Driver
    username: "sa"
    password: ""
  h2.console:
    enabled: true
    path: "/h2"

logging:
  level:
    org:
      springframework:
        web:
          socket: TRACE